development:

  clients:

    default:

      database: week1_assignment_development

      hosts:
          -  <%= ENV['MONGO_HOST'] ||= "localhost:27017" %>
      options:

  options:

test:
  clients:
    default:
      database: week1_assignment_test
      hosts:
          -  <%= ENV['MONGO_HOST'] ||= "localhost:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MLAB_URI'] %>
      options:
        conncet_timeout: 15 
