#
source 'https://rubygems.org'

gem 'rails', '4.2.8'
gem 'rails-api', '~>0.4', '>=0.4.0'
gem 'pry-rails', '~>0.3', '>=0.3.4'
gem 'rack-cors', '~>0.4', '>=0.4.0', :require => 'rack/cors'

group :development do
  gem 'spring', '~>2.0', '>=2.0.0'
end

gem 'jbuilder', '~>2.0', '>=2.0.0'

group :development, :test do
  gem 'webrick', '~>1.3.1', :platforms=>[:mingw, :mswin, :x64_mingw, :jruby]
  gem 'rspec-rails', '~>3.5', '>=3.5.2'
  # gem 'sqlite3', '~>1.3', '>=1.3.12'
  gem 'byebug', '~>9.0', '~>9.0.6'
  gem 'pry-byebug', '~>3.4', '>=3.4.0'
  gem 'httparty', '~>0.14', '>=0.14.0'
end

group :production do
  gem 'rails_12factor', '~>0.0.3'
  # gem 'pg', '~> 0.19', '>=0.19.0'
end

gem 'mongoid', '~> 5.0.0'
gem 'pg', '~> 0.19', '>=0.19.0'
# gem 'puma', '~>3.6', '>=3.6.0', :platforms=>:ruby
gem 'puma', '~>3.8.2',:platforms=>:ruby

# if you are using sqlite then you have to run bundle --without production
